Fix missing file for release:clients command
paysera/util-raml-code-generator pull request #81
Opened 2020-09-28 13:23 UTC by munza

The `release:clients` command was failing because `raml-code-generator` phar file was removed from the root directory. Instead an application command file was created at `bin/raml-code-generator`.

The file location in `src/Paysera/Bundle/ClientReleaseBundle/Service/ReleaseStep/GeneratePhpClientStep.php` is fixed.
Also, a simple test is added to check the existence of the required file and fail when the file is not in the expected location.

2020-10-05 15:09 UTC, shahariaazam commented
CC: @tomas7777

2020-10-07 11:35 UTC, vbartusevicius requested changes

2020-10-07 11:35 UTC, vbartusevicius commented on src/Paysera/Bundle/ClientReleaseBundle/Service/ReleaseStep/GeneratePhpClientStep.php
> +            'bin/raml-code-generator',
The `raml-code-generator` should be globally installed, not in the bin dir of every project

2020-10-07 11:41 UTC, vbartusevicius commented on src/Paysera/Bundle/ClientReleaseBundle/Service/ReleaseStep/GeneratePhpClientStep.php
> +            'bin/raml-code-generator',
maybe it should try to look for globally installed and local binary.

2021-01-21 06:22 UTC, closed without merging

2021-02-12 12:29 UTC, shahariaazam commented
Updated fix at #103